# Generated by Django 5.1.6 on 2025-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employees_dept_alter_employees_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
